In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Crimes_-_2001_to_present.csv')

In [3]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Longitude,Location,Historical Wards 2003-2015,Zip Codes,Community Areas,Census Tracts,Wards,Boundaries - ZIP Codes,Police Districts,Police Beats
0,24761,JC444497,09/22/2019 11:52:00 PM,030XX N KIMBALL AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,-87.712401,"(41.936274201, -87.712400898)",15.0,21538.0,22.0,55.0,12.0,39.0,7.0,168.0
1,11837612,JC444514,09/22/2019 11:45:00 PM,004XX W 111TH ST,143A,WEAPONS VIOLATION,UNLAWFUL POSS OF HANDGUN,STREET,True,False,...,-87.634289,"(41.692454712, -87.634288569)",45.0,21861.0,45.0,525.0,22.0,19.0,9.0,258.0
2,11838692,JC444512,09/22/2019 11:45:00 PM,039XX W MONTROSE AVE,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,BAR OR TAVERN,False,False,...,-87.725967,"(41.960970619, -87.725967322)",28.0,21538.0,16.0,117.0,38.0,39.0,1.0,9.0
3,11837693,JC444507,09/22/2019 11:42:00 PM,064XX S LAFLIN ST,0810,THEFT,OVER $500,RESIDENCE,False,True,...,-87.661712,"(41.776937286, -87.661711588)",17.0,22257.0,65.0,279.0,2.0,23.0,17.0,204.0
4,11837630,JC444521,09/22/2019 11:40:00 PM,024XX E 79TH ST,2016,NARCOTICS,MANU/DELIVER:PCP,STREET,True,False,...,-87.564609,"(41.751753433, -87.564608821)",43.0,21202.0,39.0,246.0,37.0,24.0,19.0,225.0

In [4]:
df.shape

(6975703, 30)

In [5]:
df.dtypes

ID                              int64
Case Number                    object
Date                           object
Block                          object
IUCR                           object
Primary Type                   object
Description                    object
Location Description           object
Arrest                           bool
Domestic                         bool
Beat                            int64
District                      float64
Ward                          float64
Community Area                float64
FBI Code                       object
X Coordinate                  float64
Y Coordinate                  float64
Year                            int64
Updated On                     object
Latitude                      float64
Longitude                     float64
Location                       object
Historical Wards 2003-2015    float64
Zip Codes                     float64
Community Areas               float64
Census Tracts                 float64
Wards                         float64
Boundaries - ZIP Codes        float64
Police Districts              float64
Police Beats                  float64
dtype: object

In [7]:
df.Arrest.value_counts()

False    5055192
True     1920511
Name: Arrest, dtype: int64

In [9]:
cols = df.columns

In [12]:
df.Block.value_counts()

100XX W OHARE ST                       15497
001XX N STATE ST                       13167
076XX S CICERO AVE                      9439
008XX N MICHIGAN AVE                    8723
0000X N STATE ST                        8272
023XX S STATE ST                        5216
064XX S DR MARTIN LUTHER KING JR DR     5171
063XX S DR MARTIN LUTHER KING JR DR     5110
0000X W TERMINAL ST                     4995
001XX W 87TH ST                         4258
008XX N STATE ST                        4130
022XX S STATE ST                        3995
012XX S WABASH AVE                      3817
0000X S STATE ST                        3796
006XX N MICHIGAN AVE                    3752
009XX W BELMONT AVE                     3682
057XX S CICERO AVE                      3556
038XX W ROOSEVELT RD                    3480
011XX W WILSON AVE                      3397
002XX W 87TH ST                         3390
075XX S STONY ISLAND AVE                3361
071XX S JEFFERY BLVD                    3351
0000X W 95TH ST                         3327
046XX W NORTH AVE                       3314
005XX E BROWNING AVE                    3304
007XX N MICHIGAN AVE                    3229
005XX N MICHIGAN AVE                    3190
040XX W LAKE ST                         3188
085XX S COTTAGE GROVE AVE               3131
065XX S DR MARTIN LUTHER KING JR DR     3096
                                       ...
008XX W Roscoe st                          1
112XX S CALUMET RIVER                      1
029XX W LUNT AV                            1
109XX S HAMLIN AV                          1
009XX W 109 PL                             1
092XX S CONSTANCE AV                       1
061XX W Leland Ave                         1
071XX N LEHIGH AVE                         1
072XX S woodlawn ave                       1
008XX  LEXINGTON CIRCLE                    1
055XX S AUSTIN AV                          1
071XX W WELLINGTON AV                      1
003XX E 40 ST                              1
030XX S CALIFORNIA                         1
003XX E 88 ST                              1
027XX W 109 ST                             1
059XX S ST LAWRENCE AV                     1
024XX W 49 ST                              1
109XX S BISHOP FORD EXPY OB                1
018XX W 70 ST                              1
011XX S Clark st                           1
105XX S GLENROY AVE                        1
003XX W Webster Ave                        1
030XX W Carroll Ave                        1
027XX N Lakewood Ave                       1
045XX W 60 ST                              1
015XX N Leavitt St                         1
030XX S CALIFORNIA BL                      1
008XX S KILPATRICK AV                      1
067XX W ARMITAGE AV                        1
Name: Block, Length: 60505, dtype: int64

In [13]:
df.IUCR.value_counts()

0820    566880
0486    538007
0460    517088
1320    373348
1310    366059
0810    361105
0560    302607
1811    277777
0610    267843
0910    253240
0890    236226
0860    176523
2820    137676
1330    123288
2027    120435
0620    105942
2825    102641
2024     94318
031A     92898
0320     91143
0430     69538
1150     56592
143A     50589
051A     48375
1506     47776
0840     44531
041A     37785
5002     37429
1350     36704
0870     35264
         ...
3770         6
5013         6
1860         6
1681         6
1572         6
0490         5
0510         5
3961         5
0493         5
2060         5
0492         5
1440         5
1697         4
5094         4
5120         4
1476         4
5122         4
0272         3
0494         3
0141         3
5113         3
1625         2
1640         2
1578         2
9901         1
0830         1
1521         1
4750         1
1633         1
1624         1
Name: IUCR, Length: 402, dtype: int64

In [14]:
df['Primary Type'].value_counts()

THEFT                                1472295
BATTERY                              1275384
CRIMINAL DAMAGE                       794691
NARCOTICS                             723526
ASSAULT                               436450
OTHER OFFENSE                         433346
BURGLARY                              396448
MOTOR VEHICLE THEFT                   322205
DECEPTIVE PRACTICE                    279804
ROBBERY                               262656
CRIMINAL TRESPASS                     199270
WEAPONS VIOLATION                      76139
PROSTITUTION                           68927
PUBLIC PEACE VIOLATION                 49145
OFFENSE INVOLVING CHILDREN             47566
CRIM SEXUAL ASSAULT                    28698
SEX OFFENSE                            26285
INTERFERENCE WITH PUBLIC OFFICER       16489
GAMBLING                               14547
LIQUOR LAW VIOLATION                   14262
ARSON                                  11472
HOMICIDE                                9910
KIDNAPPING                              6816
INTIMIDATION                            4091
STALKING                                3581
OBSCENITY                                628
CONCEALED CARRY LICENSE VIOLATION        472
PUBLIC INDECENCY                         171
NON-CRIMINAL                             171
OTHER NARCOTIC VIOLATION                 128
HUMAN TRAFFICKING                         59
NON - CRIMINAL                            38
RITUALISM                                 23
NON-CRIMINAL (SUBJECT SPECIFIED)           9
DOMESTIC VIOLENCE                          1
Name: Primary Type, dtype: int64

In [15]:
df.Description.value_counts()

SIMPLE                                          822692
$500 AND UNDER                                  566865
DOMESTIC BATTERY SIMPLE                         538007
TO VEHICLE                                      386133
TO PROPERTY                                     366059
OVER $500                                       361092
POSS: CANNABIS 30GMS OR LESS                    277777
FORCIBLE ENTRY                                  267843
AUTOMOBILE                                      253240
FROM BUILDING                                   236226
RETAIL THEFT                                    176523
TELEPHONE THREAT                                137676
TO LAND                                         123288
POSS: CRACK                                     120435
UNLAWFUL ENTRY                                  105942
HARASSMENT BY TELEPHONE                         102641
AGGRAVATED: OTHER DANG WEAPON                    95752
POSS: HEROIN(WHITE)                              94318
ARMED: HANDGUN                                   92898
STRONGARM - NO WEAPON                            91143
AGGRAVATED: HANDGUN                              87889
AGGRAVATED:KNIFE/CUTTING INSTR                   58783
CREDIT CARD FRAUD                                56592
UNLAWFUL POSS OF HANDGUN                         50589
SOLICIT ON PUBLIC WAY                            47776
FINANCIAL ID THEFT: OVER $300                    44531
OTHER VEHICLE OFFENSE                            37429
TO STATE SUP LAND                                36704
POCKET-PICKING                                   35264
VIOLATE ORDER OF PROTECTION                      35091
                                                 ...
ADULTRY                                              6
LOTTERY/OTHER                                        6
LOTTERY/PARLAY CARDS                                 6
ATT AGG CRIM SEXUAL ABUSE                            6
VIOLATION OF SUMMARY CLOSURE                         6
AGG RITUAL MUT:HANDGUN                               5
FAIL REGISTER LIC:CONT SUBS                          5
AGG RITUAL MUT:OTH DANG WEAPON                       5
REGISTER OF SALES BY DEALER                          5
AGG RITUAL MUT:KNIFE/CUTTING I                       5
AGG RIT MUT: HANDS/FIST/FEET SERIOUS INJURY          5
INTIMIDATION OF LAW ENFORCEMENT OFFICIAL             5
ARSONIST: FAIL TO REGISTER NEW ADDRESS               4
FOUND PASSPORT                                       4
USE OF METAL PIERCING BULLETS                        4
ARSONIST: DUTY TO REGISTER                           4
POLICY/OTHER                                         4
AGG RIT MUT: HANDS/FIST/FEET NO/MINOR INJURY         3
ATTEMPT AGG: OTHER FIREARM                           3
GUN OFFENDER NOTIFICATION-NO CONTACT                 3
INVOLUNTARY MANSLAUGHTER                             3
REGISTER FED GAMBLING STAMP                          2
MARRYING A BIGAMIST                                  2
NATIONAL LOTTERY                                     2
KEEP PLACE OF JUV PROSTITUTION                       1
DISCLOSE DV VICTIM LOCATION                          1
SPORTS TAMPERING                                     1
THEFT RETAIL                                         1
LOTTERY/PARI-MUTUEL                                  1
DOMESTIC VIOLENCE                                    1
Name: Description, Length: 380, dtype: int64

In [16]:
df.Domestic.value_counts()

False    6052323
True      923380
Name: Domestic, dtype: int64

In [38]:
df['Police Beats'].value_counts()

225.0    52500
238.0    52085
227.0    48370
250.0    46741
276.0    46489
74.0     46340
66.0     46242
137.0    46210
222.0    44226
195.0    42228
229.0    41787
97.0     41336
230.0    40685
274.0    40516
256.0    39826
206.0    38711
81.0     38622
235.0    38222
266.0    38018
82.0     37902
69.0     37595
208.0    37019
267.0    36944
101.0    36738
277.0    36695
65.0     36614
141.0    36529
241.0    36508
207.0    36391
155.0    36204
         ...
17.0     15991
138.0    15901
173.0    15578
39.0     15572
14.0     15509
96.0     15106
132.0    15006
166.0    14785
29.0     14153
255.0    13301
55.0     12572
189.0    12236
61.0     12211
44.0     12110
196.0    12091
34.0     11401
42.0     11369
36.0     11123
47.0     11036
59.0     10317
49.0     10276
45.0      9884
38.0      7063
40.0      3728
3.0       2839
22.0      2578
2.0       1469
16.0       974
56.0        41
264.0        4
Name: Police Beats, Length: 277, dtype: int64

In [36]:
df.Beat.unique().sum()

385639

In [25]:
df.District.unique()

array([14., 22., 17.,  7.,  4., 10.,  2.,  8.,  1., 19.,  6., 25., 15.,
       12., 11., 24.,  9.,  5.,  3., 16., 20., 18., 31., nan, 21.])

In [26]:
# District and Police Districts seems to be the same districts.

# Let's check whether we can merge them to reduce the total number of nans which are present in both column. They
# might have complementary information

df['Police Districts'].unique()

array([ 7.,  9.,  1., 17., 19., nan, 24., 21., 13., 22.,  5., 20.,  6.,
       25., 15., 16., 11., 23., 10., 18., 12.,  2., 14.,  4.,  3.,  8.])

In [19]:
df.Ward.value_counts()

28.0    291285
42.0    260524
24.0    250811
2.0     241999
27.0    233308
17.0    212172
20.0    209736
6.0     206374
3.0     194349
21.0    192031
16.0    183114
34.0    178898
15.0    173869
8.0     171735
37.0    171325
7.0     169599
9.0     161439
5.0     151443
29.0    147318
1.0     123122
4.0     119549
26.0    108784
10.0    108486
32.0    108391
18.0    106734
49.0     89742
30.0     88728
31.0     88623
25.0     88010
44.0     87984
11.0     87127
14.0     86542
46.0     84886
35.0     84479
23.0     82704
43.0     81024
13.0     80453
12.0     77466
22.0     73690
38.0     67469
36.0     66277
41.0     66053
40.0     65937
47.0     65756
50.0     64830
45.0     64522
33.0     63190
48.0     63097
39.0     59452
19.0     56442
Name: Ward, dtype: int64

In [20]:
df['Zip Codes'].value_counts()

21861.0    302332
21554.0    297979
21572.0    267286
22216.0    263942
21546.0    258411
21202.0    254151
21569.0    250916
22257.0    243720
4299.0     233010
22260.0    228440
14924.0    220594
21867.0    217287
21559.0    213143
22538.0    197482
22535.0    189209
22615.0    188266
21184.0    174560
14920.0    157176
22248.0    146229
21538.0    136166
21560.0    135896
22212.0    118698
4301.0     117009
21194.0    115804
21190.0    113650
22616.0    112398
22618.0    111666
21192.0    103780
21849.0     97962
21853.0     96780
            ...
22243.0     20776
14912.0     19697
22532.0     19567
4448.0      18704
4452.0      16302
22250.0     15543
4453.0       2257
4458.0       1967
26615.0      1702
4459.0       1679
15610.0      1009
10417.0       599
2733.0        573
4456.0        546
10408.0       488
26609.0       449
10412.0       361
21273.0       162
26633.0       162
4457.0        144
16174.0       141
9012.0        110
16181.0        99
10505.0        98
4455.0         43
21642.0        41
9460.0         29
26912.0        11
9458.0          6
4094.0          2
Name: Zip Codes, Length: 83, dtype: int64

In [42]:
df.isnull().sum()

ID                                 0
Case Number                        4
Date                               0
Block                              0
IUCR                               0
Primary Type                       0
Description                        0
Location Description            5592
Arrest                             0
Domestic                           0
Beat                               0
District                          47
Ward                          614825
Community Area                613494
FBI Code                           0
X Coordinate                   66258
Y Coordinate                   66258
Year                               0
Updated On                         0
Latitude                       66258
Longitude                      66258
Location                       66258
Historical Wards 2003-2015     86321
Zip Codes                      66258
Community Areas                83565
Census Tracts                  81417
Wards                          83452
Boundaries - ZIP Codes         83518
Police Districts               82486
Police Beats                   82463
dtype: int64

In [40]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Longitude,Location,Historical Wards 2003-2015,Zip Codes,Community Areas,Census Tracts,Wards,Boundaries - ZIP Codes,Police Districts,Police Beats
0,24761,JC444497,09/22/2019 11:52:00 PM,030XX N KIMBALL AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,-87.712401,"(41.936274201, -87.712400898)",15.0,21538.0,22.0,55.0,12.0,39.0,7.0,168.0
1,11837612,JC444514,09/22/2019 11:45:00 PM,004XX W 111TH ST,143A,WEAPONS VIOLATION,UNLAWFUL POSS OF HANDGUN,STREET,True,False,...,-87.634289,"(41.692454712, -87.634288569)",45.0,21861.0,45.0,525.0,22.0,19.0,9.0,258.0
2,11838692,JC444512,09/22/2019 11:45:00 PM,039XX W MONTROSE AVE,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,BAR OR TAVERN,False,False,...,-87.725967,"(41.960970619, -87.725967322)",28.0,21538.0,16.0,117.0,38.0,39.0,1.0,9.0
3,11837693,JC444507,09/22/2019 11:42:00 PM,064XX S LAFLIN ST,0810,THEFT,OVER $500,RESIDENCE,False,True,...,-87.661712,"(41.776937286, -87.661711588)",17.0,22257.0,65.0,279.0,2.0,23.0,17.0,204.0
4,11837630,JC444521,09/22/2019 11:40:00 PM,024XX E 79TH ST,2016,NARCOTICS,MANU/DELIVER:PCP,STREET,True,False,...,-87.564609,"(41.751753433, -87.564608821)",43.0,21202.0,39.0,246.0,37.0,24.0,19.0,225.0

In [50]:
# dropping the columns with duplicated information and most nans = Ward , Community Area
df.drop(columns=['Ward', 'Community Area'], inplace=True)

In [52]:
df.shape

(6975703, 28)

In [53]:
# If I drop all empty columns a I will only lose 1,5% of the dataset, which is very little.
# So I'll do it
df.dropna().shape[0]/df.shape[0]

0.9860968851454829

In [54]:
# Dropping all na

df = df.dropna()

In [55]:
df.shape

(6878719, 28)

In [56]:
df1 = pd.read_csv('Chicago_Police_Department_-_Illinois_Uniform_Crime_Reporting__IUCR__Codes.csv')

In [57]:
df1.head()

  IUCR  PRIMARY DESCRIPTION     SECONDARY DESCRIPTION INDEX CODE
0  110             HOMICIDE       FIRST DEGREE MURDER          I
1  130             HOMICIDE      SECOND DEGREE MURDER          I
2  141             HOMICIDE  INVOLUNTARY MANSLAUGHTER          N
3  142             HOMICIDE         RECKLESS HOMICIDE          N
4  261  CRIM SEXUAL ASSAULT       AGGRAVATED: HANDGUN          I

In [64]:
df.IUCR.value_counts()

0820    559836
0486    534832
0460    511960
1320    369958
1310    363237
0810    356059
0560    299925
1811    274938
0610    265908
0910    249994
0890    233297
0860    172804
2820    136288
1330    122281
2027    118829
0620    105206
2825    101295
2024     93050
031A     91994
0320     90344
0430     68949
1150     55503
143A     50211
051A     48025
1506     47205
0840     40107
041A     37513
5002     36858
1350     36417
4387     34799
         ...
1860         6
1627         6
1160         6
5013         6
1572         6
0492         5
2060         5
0490         5
5005         5
3961         5
0493         5
1440         5
0510         4
5094         4
5120         4
1697         4
1476         4
0272         3
5122         3
0141         3
0494         3
5113         3
1640         2
1625         2
1521         1
9901         1
0830         1
4750         1
1578         1
1633         1
Name: IUCR, Length: 401, dtype: int64

In [62]:
df1.IUCR.value_counts()

5111    1
1631    1
1531    1
1725    1
1090    1
491     1
1230    1
1151    1
2025    1
1574    1
1320    1
5110    1
1507    1
1590    1
1578    1
2230    1
3610    1
4386    1
1537    1
1611    1
2020    1
320     1
4625    1
1624    1
337     1
494     1
1512    1
1632    1
1621    1
2019    1
       ..
553     1
910     1
1651    1
860     1
938     1
895     1
330     1
4420    1
142A    1
451     1
556     1
1195    1
2095    1
2851    1
1477    1
520     1
1691    1
1750    1
1122    1
334     1
3800    1
420     1
430     1
545     1
5122    1
620     1
1695    1
2895    1
1513    1
1121    1
Name: IUCR, Length: 401, dtype: int64

In [58]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Longitude,Location,Historical Wards 2003-2015,Zip Codes,Community Areas,Census Tracts,Wards,Boundaries - ZIP Codes,Police Districts,Police Beats
0,24761,JC444497,09/22/2019 11:52:00 PM,030XX N KIMBALL AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,-87.712401,"(41.936274201, -87.712400898)",15.0,21538.0,22.0,55.0,12.0,39.0,7.0,168.0
1,11837612,JC444514,09/22/2019 11:45:00 PM,004XX W 111TH ST,143A,WEAPONS VIOLATION,UNLAWFUL POSS OF HANDGUN,STREET,True,False,...,-87.634289,"(41.692454712, -87.634288569)",45.0,21861.0,45.0,525.0,22.0,19.0,9.0,258.0
2,11838692,JC444512,09/22/2019 11:45:00 PM,039XX W MONTROSE AVE,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,BAR OR TAVERN,False,False,...,-87.725967,"(41.960970619, -87.725967322)",28.0,21538.0,16.0,117.0,38.0,39.0,1.0,9.0
3,11837693,JC444507,09/22/2019 11:42:00 PM,064XX S LAFLIN ST,0810,THEFT,OVER $500,RESIDENCE,False,True,...,-87.661712,"(41.776937286, -87.661711588)",17.0,22257.0,65.0,279.0,2.0,23.0,17.0,204.0
4,11837630,JC444521,09/22/2019 11:40:00 PM,024XX E 79TH ST,2016,NARCOTICS,MANU/DELIVER:PCP,STREET,True,False,...,-87.564609,"(41.751753433, -87.564608821)",43.0,21202.0,39.0,246.0,37.0,24.0,19.0,225.0

In [65]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Longitude,Location,Historical Wards 2003-2015,Zip Codes,Community Areas,Census Tracts,Wards,Boundaries - ZIP Codes,Police Districts,Police Beats
0,24761,JC444497,09/22/2019 11:52:00 PM,030XX N KIMBALL AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,-87.712401,"(41.936274201, -87.712400898)",15.0,21538.0,22.0,55.0,12.0,39.0,7.0,168.0
1,11837612,JC444514,09/22/2019 11:45:00 PM,004XX W 111TH ST,143A,WEAPONS VIOLATION,UNLAWFUL POSS OF HANDGUN,STREET,True,False,...,-87.634289,"(41.692454712, -87.634288569)",45.0,21861.0,45.0,525.0,22.0,19.0,9.0,258.0
2,11838692,JC444512,09/22/2019 11:45:00 PM,039XX W MONTROSE AVE,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,BAR OR TAVERN,False,False,...,-87.725967,"(41.960970619, -87.725967322)",28.0,21538.0,16.0,117.0,38.0,39.0,1.0,9.0
3,11837693,JC444507,09/22/2019 11:42:00 PM,064XX S LAFLIN ST,0810,THEFT,OVER $500,RESIDENCE,False,True,...,-87.661712,"(41.776937286, -87.661711588)",17.0,22257.0,65.0,279.0,2.0,23.0,17.0,204.0
4,11837630,JC444521,09/22/2019 11:40:00 PM,024XX E 79TH ST,2016,NARCOTICS,MANU/DELIVER:PCP,STREET,True,False,...,-87.564609,"(41.751753433, -87.564608821)",43.0,21202.0,39.0,246.0,37.0,24.0,19.0,225.0

In [68]:
# No null values
df.isnull().sum()

ID                            0
Case Number                   0
Date                          0
Block                         0
IUCR                          0
Primary Type                  0
Description                   0
Location Description          0
Arrest                        0
Domestic                      0
Beat                          0
District                      0
FBI Code                      0
X Coordinate                  0
Y Coordinate                  0
Year                          0
Updated On                    0
Latitude                      0
Longitude                     0
Location                      0
Historical Wards 2003-2015    0
Zip Codes                     0
Community Areas               0
Census Tracts                 0
Wards                         0
Boundaries - ZIP Codes        0
Police Districts              0
Police Beats                  0
dtype: int64

In [82]:
len(df['Historical Wards 2003-2015'].unique())

50

In [83]:
# Both columns has the same data so I'll drop Hist. Wards
len(df.Wards.unique())

50

In [84]:
# Dropping Column


df.drop(columns=['Historical Wards 2003-2015'], inplace=True)

In [85]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Latitude,Longitude,Location,Zip Codes,Community Areas,Census Tracts,Wards,Boundaries - ZIP Codes,Police Districts,Police Beats
0,24761,JC444497,09/22/2019 11:52:00 PM,030XX N KIMBALL AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,41.936274,-87.712401,"(41.936274201, -87.712400898)",21538.0,22.0,55.0,12.0,39.0,7.0,168.0
1,11837612,JC444514,09/22/2019 11:45:00 PM,004XX W 111TH ST,143A,WEAPONS VIOLATION,UNLAWFUL POSS OF HANDGUN,STREET,True,False,...,41.692455,-87.634289,"(41.692454712, -87.634288569)",21861.0,45.0,525.0,22.0,19.0,9.0,258.0
2,11838692,JC444512,09/22/2019 11:45:00 PM,039XX W MONTROSE AVE,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,BAR OR TAVERN,False,False,...,41.960971,-87.725967,"(41.960970619, -87.725967322)",21538.0,16.0,117.0,38.0,39.0,1.0,9.0
3,11837693,JC444507,09/22/2019 11:42:00 PM,064XX S LAFLIN ST,0810,THEFT,OVER $500,RESIDENCE,False,True,...,41.776937,-87.661712,"(41.776937286, -87.661711588)",22257.0,65.0,279.0,2.0,23.0,17.0,204.0
4,11837630,JC444521,09/22/2019 11:40:00 PM,024XX E 79TH ST,2016,NARCOTICS,MANU/DELIVER:PCP,STREET,True,False,...,41.751753,-87.564609,"(41.751753433, -87.564608821)",21202.0,39.0,246.0,37.0,24.0,19.0,225.0

In [86]:
df.dtypes

ID                          int64
Case Number                object
Date                       object
Block                      object
IUCR                       object
Primary Type               object
Description                object
Location Description       object
Arrest                       bool
Domestic                     bool
Beat                        int64
District                  float64
FBI Code                   object
X Coordinate              float64
Y Coordinate              float64
Year                        int64
Updated On                 object
Latitude                  float64
Longitude                 float64
Location                   object
Zip Codes                 float64
Community Areas           float64
Census Tracts             float64
Wards                     float64
Boundaries - ZIP Codes    float64
Police Districts          float64
Police Beats              float64
dtype: object

In [134]:
df['Beat']

0          1412
1          2233
2          1723
3           725
4           421
5           414
6          1723
8           421
9           231
10         1013
11          832
12          234
13          421
14          133
15         1913
16          735
17          621
18         2522
19          834
20          221
21          614
22         2222
23         1522
24         1233
25          131
26         1214
27          423
28         1124
29          213
30         2533
           ...
6975627    2024
6975628    1224
6975629    2535
6975630     523
6975631    2534
6975632     511
6975633     512
6975634     715
6975636    1421
6975638     211
6975640     825
6975642     422
6975644     734
6975646    1021
6975648    1022
6975650     111
6975652    1021
6975654    2233
6975656    1222
6975658    1112
6975660    1513
6975662    1431
6975664     813
6975666    2424
6975668     713
6975670     932
6975672    2124
6975674    1213
6975676     835
6975678     913
Name: Beat, Length: 6878719, dtype: int64

In [135]:
df.corr()

,ID,Arrest,Domestic,Beat,District,X Coordinate,Y Coordinate,Year,Latitude,Longitude,Zip Codes,Community Areas,Census Tracts,Wards,Boundaries - ZIP Codes,Police Districts,Police Beats,Hour,Month,Weekday
ID,1.000000,-0.059100,0.046791,-0.037678,-0.005767,0.002713,-0.003731,0.988971,-0.003735,0.002676,0.000435,0.014684,0.000072,0.011286,0.012538,0.005926,0.001253,-0.008259,0.029983,0.005518
Arrest,-0.059100,1.000000,-0.069132,-0.016682,-0.017622,-0.032937,0.000889,-0.060120,0.001021,-0.033174,-0.000135,-0.034764,0.006543,-0.016612,0.003031,0.064762,-0.013524,0.080498,-0.021136,-0.006033
Domestic,0.046791,-0.069132,1.000000,-0.042130,-0.038870,0.005377,-0.080275,0.048642,-0.080123,0.004147,0.033478,0.018862,0.001213,-0.017677,0.011946,0.031516,0.071532,-0.031015,-0.011098,0.032586
Beat,-0.037678,-0.016682,-0.042130,1.000000,0.940231,-0.505037,0.637599,-0.039563,0.638193,-0.499543,-0.102709,-0.187866,0.014457,0.082352,-0.338548,-0.606072,-0.403296,-0.008106,0.002482,0.012237
District,-0.005767,-0.017622,-0.038870,0.940231,1.000000,-0.561204,0.645649,-0.006979,0.646448,-0.556078,-0.090573,-0.123339,0.021627,0.101432,-0.338962,-0.659285,-0.383408,-0.007929,0.003100,0.013966
X Coordinate,0.002713,-0.032937,0.005377,-0.505037,-0.561204,1.000000,-0.557954,0.003841,-0.560629,0.999918,0.048736,0.162894,-0.083217,0.083971,0.136327,0.279661,0.412179,-0.002406,0.001201,-0.005984
Y Coordinate,-0.003731,0.000889,-0.080275,0.637599,0.645649,-0.557954,1.000000,-0.003290,0.999995,-0.547362,-0.163579,-0.485924,-0.025896,0.047280,-0.235137,-0.391172,-0.777699,-0.005521,0.001666,0.010359
Year,0.988971,-0.060120,0.048642,-0.039563,-0.006979,0.003841,-0.003290,1.000000,-0.003300,0.003822,-0.000399,0.013525,-0.000390,0.011388,0.013093,0.007360,0.000336,-0.007544,-0.025320,0.006200
Latitude,-0.003735,0.001021,-0.080123,0.638193,0.646448,-0.560629,0.999995,-0.003300,1.000000,-0.550059,-0.163413,-0.485472,-0.025531,0.046802,-0.235141,-0.391431,-0.777610,-0.005497,0.001658,0.010360
Longitude,0.002676,-0.033174,0.004147,-0.499543,-0.556078,0.999918,-0.547362,0.003822,-0.550059,1.000000,0.046509,0.157095,-0.084340,0.085046,0.133994,0.276142,0.403728,-0.002510,0.001239,-0.005868
Zip Codes,0.000435,-0.000135,0.033478,-0.102709,-0.090573,0.048736,-0.163579,-0.000399,-0.163413,0.046509,1.000000,0.037148,-0.024243,-0.096491,0.076165,-0.021533,0.228502,0.007710,-0.001573,-0.007710
Community Areas,0.014684,-0.034764,0.018862,-0.187866,-0.123339,0.162894,-0.485924,0.013525,-0.485472,0.157095,0.037148,1.000000,0.158669,-0.043364,0.124800,0.005062,0.413042,-0.009217,0.001936,0.003904
Census Tracts,0.000072,0.006543,0.001213,0.014457,0.021627,-0.083217,-0.025896,-0.000390,-0.025531,-0.084340,-0.024243,0.158669,1.000000,0.013092,0.011006,0.044082,-0.081934,-0.004072,0.001709,0.005780
Wards,0.011286,-0.016612,-0.017677,0.082352,0.101432,0.083971,0.047280,0.011388,0.046802,0.085046,-0.096491,-0.043364,0.013092,1.000000,-0.199136,-0.195855,-0.030465,-0.004407,0.001887,0.000456
Boundaries - ZIP Codes,0.012538,0.003031,0.011946,-0.338548,-0.338962,0.136327,-0.235137,0.013093,-0.235141,0.133994,0.076165,0.124800,0.011006,-0.199136,1.000000,0.359429,0.141292,-0.006614,-0.002239,0.000925
Police Districts,0.005926,0.064762,0.031516,-0.606072,-0.659285,0.279661,-0.391172,0.007360,-0.391431,0.276142,-0.021533,0.005062,0.044082,-0.195855,0.359429,1.000000,0.158808,0.010576,-0.004054,-0.008451
Police Beats,0.001253,-0.013524,0.071532,-0.403296,-0.383408,0.412179,-0.777699,0.000336,-0.777610,0.403728,0.228502,0.413042,-0.081934,-0.030465,0.141292,0.158808,1.000000,0.001036,-0.000572,-0.005271
Hour,-0.008259,0.080498,-0.031015,-0.008106,-0.007929,-0.002406,-0.005521,-0.007544,-0.005497,-0.002510,0.007710,-0.009217,-0.004072,-0.004407,-0.006614,0.010576,0.001036,1.000000,-0.000262,-0.038807
Month,0.029983,-0.021136,-0.011098,0.002482,0.003100,0.001201,0.001666,-0.025320,0.001658,0.001239,-0.001573,0.001936,0.001709,0.001887,-0.002239,-0.004054,-0.000572,-0.000262,1.000000,0.004186
Weekday,0.005518,-0.006033,0.032586,0.012237,0.013966,-0.005984,0.010359,0.006200,0.010360,-0.005868,-0.007710,0.003904,0.005780,0.000456,0.000925,-0.008451,-0.005271,-0.038807,0.004186,1.000000

In [104]:
# cols are not the same

(df['Police Districts'] == df.District).sum()

1832

In [103]:
# Cols are not the same

(df['Police Beats'] == df.Beat).sum()

0

In [101]:
# Columns X & Y Coordinates are not the same as the Long and  Lat columns

(df['X Coordinate'] != df.Longitude).sum()

6878719

In [98]:
(df['X Coordinate'] != df.Latitude).sum()

6878719

In [88]:
df['Zip Codes'].unique()

array([21538., 21861., 22257., 21202., 21849., 21192., 21569., 22260.,
       22538., 21194., 22616., 21554., 22615.,  4300.,  4301., 22216.,
       14920.,  4446., 21184., 21560., 21853., 21546.,  4449., 22248.,
       21572., 22243., 14924., 21559.,  4448.,  4299., 22212., 22254.,
       21867.,  4460., 21190., 22268., 14310., 21186., 14917., 22535.,
       22618., 14926., 21182., 14912.,  4451., 14311., 21869., 22532.,
        4450., 14309., 22620., 16197.,  4452., 26615., 14913.,  4447.,
       22528.,  4454., 14914., 22250.,  4453.,  4458., 26633., 10408.,
        4457.,  2733.,  4456.,  4455., 10417., 15610.,  9012., 21642.,
        4459., 26912., 26609., 16174.,  4094.,  9460.])

In [89]:
# Don't understand this column, no description on data.chicago website

df['Boundaries - ZIP Codes'].unique()

array([39., 19., 23., 24., 25., 20., 10., 57., 60., 40., 15., 59.,  2.,
        8., 36., 32., 43., 55., 28.,  4.,  9., 61., 22., 56., 30., 17.,
       37., 11., 31.,  5., 13., 52., 58., 47., 16., 42., 53., 41., 44.,
        1., 21., 54.,  6., 29., 14., 34., 48., 18., 50.,  7., 12., 49.,
       38., 35., 33., 45., 51., 26.,  3., 46., 27.])

In [97]:
df.shape

(6878719, 27)

In [105]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Latitude,Longitude,Location,Zip Codes,Community Areas,Census Tracts,Wards,Boundaries - ZIP Codes,Police Districts,Police Beats
0,24761,JC444497,09/22/2019 11:52:00 PM,030XX N KIMBALL AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,41.936274,-87.712401,"(41.936274201, -87.712400898)",21538.0,22.0,55.0,12.0,39.0,7.0,168.0
1,11837612,JC444514,09/22/2019 11:45:00 PM,004XX W 111TH ST,143A,WEAPONS VIOLATION,UNLAWFUL POSS OF HANDGUN,STREET,True,False,...,41.692455,-87.634289,"(41.692454712, -87.634288569)",21861.0,45.0,525.0,22.0,19.0,9.0,258.0
2,11838692,JC444512,09/22/2019 11:45:00 PM,039XX W MONTROSE AVE,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,BAR OR TAVERN,False,False,...,41.960971,-87.725967,"(41.960970619, -87.725967322)",21538.0,16.0,117.0,38.0,39.0,1.0,9.0
3,11837693,JC444507,09/22/2019 11:42:00 PM,064XX S LAFLIN ST,0810,THEFT,OVER $500,RESIDENCE,False,True,...,41.776937,-87.661712,"(41.776937286, -87.661711588)",22257.0,65.0,279.0,2.0,23.0,17.0,204.0
4,11837630,JC444521,09/22/2019 11:40:00 PM,024XX E 79TH ST,2016,NARCOTICS,MANU/DELIVER:PCP,STREET,True,False,...,41.751753,-87.564609,"(41.751753433, -87.564608821)",21202.0,39.0,246.0,37.0,24.0,19.0,225.0

In [107]:
# Smart way of checking if the syntax works on column

# It works

pd.to_datetime(df.head(5)['Date'])

0   2019-09-22 23:52:00
1   2019-09-22 23:45:00
2   2019-09-22 23:45:00
3   2019-09-22 23:42:00
4   2019-09-22 23:40:00
Name: Date, dtype: datetime64[ns]

In [108]:
# Changing Date column into datetime64[ns]

df['Date'] = pd.to_datetime(df['Date'])

In [131]:
#Create WEEKDAY column

df['Weekday'] = df['Date'].map(lambda x : x.isoweekday())

In [117]:
#Create TIME column

df['Hour'] = df['Date'].map(lambda x: x.hour)

In [118]:
#Create MONTH column

df['Month'] = df['Date'].map(lambda x: x.month)

In [123]:
#Change YEAR column into date time
df['Year'] = df['Date'].map(lambda x: x.year)

In [130]:
# Just testing here

df['Date'][37000].isoweekday()

7

In [132]:
df.dtypes

ID                                 int64
Case Number                       object
Date                      datetime64[ns]
Block                             object
IUCR                              object
Primary Type                      object
Description                       object
Location Description              object
Arrest                              bool
Domestic                            bool
Beat                               int64
District                         float64
FBI Code                          object
X Coordinate                     float64
Y Coordinate                     float64
Year                               int64
Updated On                        object
Latitude                         float64
Longitude                        float64
Location                          object
Zip Codes                        float64
Community Areas                  float64
Census Tracts                    float64
Wards                            float64
Boundaries - ZIP Codes           float64
Police Districts                 float64
Police Beats                     float64
Hour                               int64
Month                              int64
Weekday                            int64
dtype: object

In [136]:
df.to_csv('Chicago_crimes1.csv')